language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - cd Projects/project_2_packages/wethebestOLS/wethebestOLS
install:
  - pip install -r requirements.txt
# command to run tests
before_tests:
  - cd tests
script:
  - python -m unittest
